name: nostra_casa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  animations: ^2.0.7
  easy_localization: ^3.0.2
  google_maps_flutter: ^2.3.0
  google_maps_flutter_android: ^2.4.13
  intl_phone_number_input: ^0.7.2
  pinput: ^2.2.21
  flutter_animation_progress_bar: ^2.3.1
  image_picker: ^1.0.1
  shared_preferences: ^2.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.4.3
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  csc_picker: ^0.2.7
  shimmer: ^2.0.0
  bloc_concurrency: ^0.2.2
  card_swiper: ^3.0.1
  dropdown_search: 5.0.5
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^5.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/translation/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/CAIRO-LIGHT.OTF
          weight: 200
        - asset: fonts/CAIRO-REGULAR.OTF
          weight: 400
        - asset: fonts/CAIRO-BOLD2.TTF
          weight: 800

  uses-material-design: true
